name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'config.example.**'
      - '**.sh'
      - '**.json'
      - '**.yml'
      - '!.github/workflows/**'

jobs:
  check:
    name: Review the code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check
      run: cargo check

  build:
    name: Build the binary file
    if: ${{ github.event_name != 'pull_request' && success() }}
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        docker run -i --rm \
        -v $PWD:/workdir \
        -v ~/.cargo/git:/root/.cargo/git \
        -v ~/.cargo/registry:/root/.cargo/registry \
        registry.gitlab.com/rust_musl_docker/image:stable-latest \
        cargo build --profile=fast -vv --target=x86_64-unknown-linux-musl
    - name: Upload Build Artifact
      uses: actions/upload-artifact@main
      with:
        name: biliroaming-rust-server-${{ github.run_number }}
        path: |
          ./target/x86_64-unknown-linux-musl/fast/biliroaming_rust_server
  
  alpha:
    name: Upload the Alpha test version file
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: biliroaming-rust-server-${{ github.run_number }}
    - name: Update Alpha Release
      uses: mini-bomba/create-github-release@v1.1.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        tag: alpha-releases
        name: Alpha-Release
        body: |
            This automatic prerelease is built from commit ${{ env.GIT_HASH }} and was triggered by @${{ github.actor }}
            [Github Actions workflow run that built this prerelease](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            Commit message:
            ${{ env.GIT_MESSAGE }}
        files: |
          ./biliroaming_rust_server
        clear_attachments: true

  release:
    name: Upload the binary file when it is released
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: biliroaming-rust-server-${{ github.run_number }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./biliroaming_rust_server
